### ISSUE TITLE
Whitelabelling API plugin 

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/opal-ideas#16]
Some users would like to embed certain data from elCID into other applications as html snippets in e.g. an iFrame.

> As a Developer
> I want to embed unstyled records in my application
> So that I can display information that is recorded in elCID elsewhere from GET requests
> 
> As an Administrator
> I would like to restrict access to the API
> So that we can allow people to make requests with e.g. API keys in the URL instead of Django Auth

Specific use cases:

> As a Haem doctor
> I need to see the most recent elCID Abx SOS plan for a particular patient in my Filemaker database
> So that we don't have to duplicate information stored in elCId in our own database.
> 
> As a Haem doctor
> I need to see all allergies in elCID for a particular patient in my Filemaker database
> So that we don't have to duplicate information stored in elCId in our own database.

We would expect lookup to be via a MRN (Hospital Number).
The [Adding Apis to plugins](http://opal.openhealthcare.org.uk/docs/guides/plugins/#adding-apis) docs may be helpful...

Currently there is no API key functionality - so we'll need to add / enable & document that.

**Comment by fredkingham** [comment]
the GET request will give us the hospital number, the api key that we've whitelisted and the column names of the information that they want and we'll return a list of the data

**Comment by davidmiller** [comment]
We would expect the application e.g. elCID that installs the whitelabelling plugin to add templates for record types they want to make available.

Good example templates would be : 

Demographics
Allergies
MicrobiologyInput
Diagnosis

**Comment by fredkingham** [comment]
done, details here https://github.com/openhealthcare/elcid/pull/692

**Comment by fredkingham** [comment]
@davidmiller can you take a look, see if this fits the bill

https://elcid04-test.herokuapp.com/iframeapi/?hospitalNumber=123123123&column=diagnosis&key=6RPDG476PDRK4TGGL0HLIJJAMQ0A57QSKFFOEMCXQOST3K0BH2&latest=True

**Comment by davidmiller** [comment]
@fredkingham This looks good to go and talk to the prospective users :)

Only thing left is to add it to the [Plugins list](http://opal.openhealthcare.org.uk/docs/guides/plugins_list/) - I'd probably commit that directly to opal@v0.4.2 - I think you can close this issue after that !
