### ISSUE TITLE
Set up RFH repository and application

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/opal-ideas#19]
- [x] elCID@RFH repo
- [x] Something I can log into in dev
- [x] Some RFH branding somewhere
- [x] Add setup for this application to openhealthcare/developer
- [x] Have a running application in somebody elses developer vagrant machine

**Comment by GabPoll** [comment]
I love how this is even a thing! Onwards and upwards.

**Comment by michaeledwardmarks** [comment]
Whoop!

**Comment by fredkingham** [comment]
@davidmiller the new repo for issues is https://github.com/openhealthcare/elcid-rf

**Comment by davidmiller** [comment]
Awesomes :) 
I think that RFH is more widely used - @GabPoll ?

If so maybe we could update it to elcid-rfh ?

**Comment by michaeledwardmarks** [comment]
Yes RFH

**Comment by fredkingham** [comment]
ah ok, cool, I'll change it

**Comment by GabPoll** [comment]
Yep. RFH is the commonly used abbreviation.

**Comment by davidmiller** [comment]
Done !
